# Generated by Django 5.1.15 on 2026-07-20 22:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.TextField()),
                ("contacto", models.TextField()),
                ("destino_interes", models.TextField(blank=True, null=True)),
                ("mensaje", models.TextField(blank=True, null=True)),
                (
                    "origen",
                    models.TextField(
                        choices=[
                            ("popup", "Popup de descuento"),
                            ("contacto", "Formulario de contacto"),
                            ("whatsapp", "WhatsApp"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "db_table": "leads",
            },
        ),
    ]
