# Generated by Django 5.1.15 on 2026-07-20 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="asesor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="bot_activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="datos_viaje",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="lead",
            name="estado",
            field=models.TextField(
                choices=[
                    ("nuevo", "Nuevo"),
                    ("en_conversacion", "En conversación"),
                    ("calificado", "Calificado"),
                    ("cotizado", "Cotizado"),
                    ("ganado", "Ganado"),
                    ("perdido", "Perdido"),
                ],
                default="nuevo",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="telefono",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name="lead",
            constraint=models.UniqueConstraint(
                condition=models.Q(("origen", "whatsapp")),
                fields=("telefono",),
                name="unique_telefono_whatsapp",
            ),
        ),
    ]
