# Generated by Django 5.1.15 on 2026-07-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_lead_asesor_lead_bot_activo_lead_datos_viaje_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="bot_pausado_hasta",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
