# Generated by Django 6.0.7 on 2026-07-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_lead_bot_pausado_hasta"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="ultima_notif_asesor",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
