# Generated by Django 6.0.7 on 2026-07-27 22:04

import django.db.models.deletion
import pagos.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leads", "0004_lead_ultima_notif_asesor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cliente_nombre", models.TextField()),
                ("cliente_contacto", models.TextField()),
                ("destino", models.TextField(default="")),
                ("descripcion", models.TextField(blank=True, default="")),
                ("monto", models.DecimalField(decimal_places=0, max_digits=12)),
                ("metodo_pago", models.TextField(blank=True, null=True)),
                (
                    "token",
                    models.TextField(default=pagos.models.generar_token, unique=True),
                ),
                (
                    "referencia",
                    models.TextField(
                        default=pagos.models.generar_referencia, unique=True
                    ),
                ),
                (
                    "estado",
                    models.TextField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobado", "Aprobado"),
                            ("declinado", "Declinado"),
                            ("anulado", "Anulado"),
                            ("reembolsado", "Reembolsado"),
                            ("error", "Error"),
                        ],
                        default="pendiente",
                    ),
                ),
                (
                    "wompi_transaction_id",
                    models.TextField(blank=True, null=True, unique=True),
                ),
                ("webhook_payload", models.JSONField(blank=True, null=True)),
                ("expira_en", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pagos",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "db_table": "pagos",
                "ordering": ["-created_at"],
            },
        ),
    ]
