# Generated by Django 5.1.15 on 2026-07-20 22:55

import django.db.models.deletion
import pagos.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cotizaciones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.TextField(default=pagos.models.generar_token, unique=True),
                ),
                ("monto", models.DecimalField(decimal_places=0, max_digits=12)),
                (
                    "estado",
                    models.TextField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobado", "Aprobado"),
                            ("declinado", "Declinado"),
                            ("anulado", "Anulado"),
                            ("reembolsado", "Reembolsado"),
                            ("error", "Error"),
                        ],
                        default="pendiente",
                    ),
                ),
                (
                    "wompi_transaction_id",
                    models.TextField(blank=True, null=True, unique=True),
                ),
                ("referencia", models.TextField(blank=True, null=True, unique=True)),
                ("webhook_payload", models.JSONField(blank=True, null=True)),
                ("expira_en", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cotizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos",
                        to="cotizaciones.cotizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "db_table": "pagos",
                "ordering": ["-created_at"],
            },
        ),
    ]
