# Generated by Django 6.0.7 on 2026-09-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pago",
            name="numero_identificacion",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="pago",
            name="numero_reserva_interno",
            field=models.TextField(blank=True, default=""),
        ),
    ]
