# Generated by Django 6.0.7 on 2026-07-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pago",
            name="metodo_pago",
            field=models.TextField(blank=True, null=True),
        ),
    ]
