# Generated by Django 6.0.7 on 2026-09-22 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pagos", "0002_pago_numero_identificacion_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pago",
            old_name="numero_reserva_interno",
            new_name="numero_reserva",
        ),
    ]
