# Generated by Django 5.1.15 on 2026-07-20 22:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leads", "0002_lead_asesor_lead_bot_activo_lead_datos_viaje_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mensaje",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rol",
                    models.TextField(
                        choices=[
                            ("cliente", "Cliente"),
                            ("bot", "Bot"),
                            ("asesor", "Asesor"),
                            ("sistema", "Sistema"),
                        ]
                    ),
                ),
                ("contenido", models.TextField()),
                ("wa_message_id", models.TextField(blank=True, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje",
                "verbose_name_plural": "Mensajes",
                "db_table": "mensajes",
                "ordering": ["created_at"],
            },
        ),
    ]
