# Generated by Django 5.1.15 on 2026-07-20 22:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leads", "0002_lead_asesor_lead_bot_activo_lead_datos_viaje_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cotizacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("destino", models.TextField()),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("num_personas", models.PositiveIntegerField(default=1)),
                ("precio", models.DecimalField(decimal_places=0, max_digits=12)),
                ("incluye", models.JSONField(blank=True, default=list)),
                ("no_incluye", models.JSONField(blank=True, default=list)),
                ("vigencia", models.DateField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "estado",
                    models.TextField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("generada", "Generada"),
                            ("enviada", "Enviada"),
                            ("aceptada", "Aceptada"),
                            ("rechazada", "Rechazada"),
                            ("vencida", "Vencida"),
                        ],
                        default="borrador",
                    ),
                ),
                ("pdf_url", models.TextField(blank=True, null=True)),
                ("notas", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cotizaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cotizaciones",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotización",
                "verbose_name_plural": "Cotizaciones",
                "db_table": "cotizaciones",
                "ordering": ["-created_at"],
            },
        ),
    ]
