# Generated by Django 6.0.7 on 2026-08-09 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("ciudad", models.CharField(max_length=100)),
                ("direccion", models.TextField(blank=True)),
                ("descripcion", models.TextField(blank=True)),
                ("horario_restaurante", models.CharField(blank=True, max_length=100)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hotel (catálogo)",
                "verbose_name_plural": "Hoteles (catálogo)",
                "db_table": "hoteles_partner",
                "ordering": ["nombre"],
            },
        ),
        migrations.RenameField(
            model_name="cotizacion",
            old_name="precio",
            new_name="precio_total",
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="precio_por_persona",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=12, null=True
            ),
        ),
        migrations.CreateModel(
            name="HotelImagen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="cotizaciones.hotelpartner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen de hotel",
                "verbose_name_plural": "Imágenes de hotel",
                "db_table": "hoteles_imagenes",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="CotizacionHotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_libre", models.CharField(blank=True, max_length=200)),
                ("noches", models.PositiveIntegerField()),
                ("tipo_habitacion", models.CharField(blank=True, max_length=150)),
                ("plan_alimentacion", models.CharField(blank=True, max_length=150)),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "cotizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hoteles",
                        to="cotizaciones.cotizacion",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cotizaciones_hotel",
                        to="cotizaciones.hotelpartner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotel de cotización",
                "verbose_name_plural": "Hoteles de cotización",
                "db_table": "cotizaciones_hoteles",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="Vuelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ida", "Ida"), ("vuelta", "Vuelta")], max_length=10
                    ),
                ),
                ("fecha", models.DateField()),
                ("origen", models.CharField(max_length=10)),
                ("destino", models.CharField(max_length=10)),
                ("hora_salida", models.TimeField()),
                ("hora_llegada", models.TimeField()),
                ("aerolinea", models.CharField(max_length=100)),
                ("paradas", models.PositiveIntegerField(default=0)),
                ("duracion", models.CharField(blank=True, max_length=20)),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "cotizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vuelos",
                        to="cotizaciones.cotizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vuelo",
                "verbose_name_plural": "Vuelos",
                "db_table": "cotizaciones_vuelos",
                "ordering": ["orden"],
            },
        ),
    ]
