# Generated by Django 6.0.7 on 2026-08-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cotizaciones",
            "0002_hotelpartner_rename_precio_cotizacion_precio_total_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="descripcion_destino",
            field=models.TextField(
                blank=True,
                help_text="Párrafo descriptivo del destino para la página 'Imagina despertar aquí'.",
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="imagen_destino",
            field=models.URLField(
                blank=True,
                help_text="URL pública (Supabase Storage) de la foto del destino.",
            ),
        ),
    ]
