# Generated by Django 6.0.7 on 2026-08-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0003_cotizacion_descripcion_destino_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="imagen_destino_secundaria",
            field=models.URLField(
                blank=True,
                help_text="URL pública (Supabase Storage) de la segunda foto, horizontal, debajo de la descripción.",
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="imagen_destino",
            field=models.URLField(
                blank=True,
                help_text="URL pública (Supabase Storage) de la foto principal del destino.",
            ),
        ),
    ]
