# Generated by Django 6.0.7 on 2026-08-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0004_cotizacion_imagen_destino_secundaria_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="bienvenida_descripcion",
            field=models.TextField(
                blank=True,
                help_text="Párrafo descriptivo para la página 'Bienvenidos a [destino]'.",
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="imagen_bienvenida",
            field=models.URLField(
                blank=True,
                help_text="URL pública (Supabase Storage) de la foto grande de la página Bienvenidos.",
            ),
        ),
    ]
