# Generated by Django 6.0.7 on 2026-08-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0005_cotizacion_bienvenida_descripcion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="imagen_viaje_sonado",
            field=models.URLField(
                blank=True,
                help_text="URL pública (Supabase Storage) de la foto horizontal grande de esta página.",
            ),
        ),
    ]
