# Generated by Django 6.0.7 on 2026-08-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0006_cotizacion_imagen_viaje_sonado"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="imagen_arte_vivir_1",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="imagen_arte_vivir_2",
            field=models.URLField(blank=True),
        ),
    ]
