# Generated by Django 6.0.7 on 2026-08-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0007_cotizacion_imagen_arte_vivir_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vuelo",
            name="imagen",
            field=models.URLField(
                blank=True,
                help_text="URL pública (Supabase Storage) de la captura de pantalla del vuelo (Avianca, Google Flights, etc.)",
            ),
        ),
    ]
