# Generated by Django 6.0.7 on 2026-08-10 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0008_vuelo_imagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="precio_nota_total",
            field=models.TextField(
                blank=True,
                help_text="Mensaje alternativo cuando no hay un total único, ej: 'Según la elección del hotel y adicionales, consulta el total con tu asesor'",
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="precio_total",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=12, null=True
            ),
        ),
        migrations.CreateModel(
            name="PrecioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etiqueta",
                    models.CharField(
                        help_text="Ej: 'Adultos', 'Niño', 'Tarifa sencilla', 'Estándar', 'Vista al mar'",
                        max_length=150,
                    ),
                ),
                ("precio", models.DecimalField(decimal_places=0, max_digits=12)),
                (
                    "nota",
                    models.CharField(
                        blank=True,
                        help_text="Ej: 'DESAYUNOS', 'PAGO DE CONTADO' -- se muestra debajo de la línea",
                        max_length=150,
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "cotizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precios",
                        to="cotizaciones.cotizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de precio",
                "verbose_name_plural": "Líneas de precio",
                "db_table": "cotizaciones_precios",
                "ordering": ["orden"],
            },
        ),
    ]
