# Generated by Django 6.0.7 on 2026-08-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0009_cotizacion_precio_nota_total_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DestinoContenido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre exacto del destino, ej: 'Coveñas', 'Brasil'. Se usa para buscar coincidencia al crear una cotización nueva.",
                        max_length=150,
                        unique=True,
                    ),
                ),
                ("descripcion_destino", models.TextField(blank=True)),
                ("imagen_destino", models.URLField(blank=True)),
                ("imagen_destino_secundaria", models.URLField(blank=True)),
                ("bienvenida_descripcion", models.TextField(blank=True)),
                ("imagen_bienvenida", models.URLField(blank=True)),
                ("imagen_viaje_sonado", models.URLField(blank=True)),
                ("viaje_sonado_intro_texto", models.TextField(blank=True)),
                ("viaje_sonado_texto1", models.TextField(blank=True)),
                ("imagen_arte_vivir_1", models.URLField(blank=True)),
                ("imagen_arte_vivir_2", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contenido de destino",
                "verbose_name_plural": "Contenidos de destino",
                "db_table": "destinos_contenido",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="viaje_sonado_intro_imagen",
            field=models.URLField(
                blank=True,
                help_text="URL del PNG transparente generado automáticamente a partir de viaje_sonado_intro_texto.",
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="viaje_sonado_intro_texto",
            field=models.TextField(
                blank=True,
                help_text="Párrafo 'Al llegar a [destino]...'. Se pre-llena desde DestinoContenido si existe una entrada con el mismo nombre de destino.",
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="viaje_sonado_texto1",
            field=models.TextField(
                blank=True,
                help_text="Párrafo bajo 'Disfrutas cada instante'. Se pre-llena desde DestinoContenido.",
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="viaje_sonado_texto1_imagen",
            field=models.URLField(
                blank=True,
                help_text="URL del PNG transparente generado automáticamente a partir de viaje_sonado_texto1.",
            ),
        ),
    ]
