# Generated by Django 6.0.7 on 2026-08-15 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0010_destinocontenido_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelpartner",
            name="destino",
            field=models.ForeignKey(
                blank=True,
                help_text="Destino al que pertenece este hotel. Se usa para filtrar qué hoteles mostrar al elegir un destino en el formulario.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hoteles",
                to="cotizaciones.destinocontenido",
            ),
        ),
    ]
