# Generated by Django 6.0.7 on 2026-08-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0011_hotelpartner_destino"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotelpartner",
            name="horario_restaurante",
        ),
        migrations.AddField(
            model_name="cotizacionhotel",
            name="datos_importantes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Datos importantes de la estadía, en viñetas (ej. horario de restaurante, check-in, check-out). Se carga por cotización, puede variar según el hotel/cliente. Ej: ['Horario restaurante: 6:00 A.M a 10:00 P.M', 'Check-in: 3:00 PM']",
            ),
        ),
        migrations.AddField(
            model_name="cotizacionhotel",
            name="precios",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Opciones de precio para este hotel, en viñetas de texto libre (reemplaza mostrar el precio en la página de inversión cuando hay varios hoteles a elegir). Ej: ['$2.500.000 x persona - Estándar - Alimentación: DESAYUNOS', '$2.650.000 x persona - Vista al mar']",
            ),
        ),
    ]
