# Generated by Django 6.0.7 on 2026-08-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0012_remove_hotelpartner_horario_restaurante_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="bienvenida_descripcion_imagen",
            field=models.URLField(
                blank=True,
                help_text="URL del PNG transparente generado automáticamente a partir de bienvenida_descripcion.",
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="descripcion_destino_imagen",
            field=models.URLField(
                blank=True,
                help_text="URL del PNG transparente generado automáticamente a partir de descripcion_destino.",
            ),
        ),
    ]
