# Generated by Django 6.0.7 on 2026-08-16 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0013_cotizacion_bienvenida_descripcion_imagen_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vuelo",
            name="aerolinea",
        ),
        migrations.RemoveField(
            model_name="vuelo",
            name="destino",
        ),
        migrations.RemoveField(
            model_name="vuelo",
            name="duracion",
        ),
        migrations.RemoveField(
            model_name="vuelo",
            name="fecha",
        ),
        migrations.RemoveField(
            model_name="vuelo",
            name="hora_llegada",
        ),
        migrations.RemoveField(
            model_name="vuelo",
            name="hora_salida",
        ),
        migrations.RemoveField(
            model_name="vuelo",
            name="origen",
        ),
        migrations.RemoveField(
            model_name="vuelo",
            name="paradas",
        ),
    ]
