# Generated by Django 6.0.7 on 2026-08-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0014_remove_vuelo_aerolinea_remove_vuelo_destino_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="inversion_lineas",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Líneas de precio en texto libre, una debajo de otra. Ej: ['$ 9.600.000 Tarifa sencilla', '$ 6.800.000 Tarifa doble']. Solo aplica si la cotización tiene 0 o 1 hotel -- con 2+, la página de inversión muestra un mensaje fijo en su lugar.",
            ),
        ),
    ]
