# Generated by Django 6.0.7 on 2026-08-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0015_cotizacion_inversion_lineas"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="destino_buenviaje_imagen",
            field=models.URLField(
                blank=True,
                help_text="PNG transparente del destino, estilo normal de buenviaje.",
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="destino_portada_imagen",
            field=models.URLField(
                blank=True,
                help_text="PNG transparente del destino, estilo itálico de portada.",
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="fecha_viaje_imagen",
            field=models.URLField(
                blank=True,
                help_text="PNG transparente con el rango de fechas, compartido entre portada y buenviaje.",
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="lead_nombre_imagen",
            field=models.URLField(
                blank=True,
                help_text="PNG transparente con el nombre del cliente, compartido entre portada y buenviaje.",
            ),
        ),
    ]
