# Generated by Django 6.0.7 on 2026-08-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0016_cotizacion_destino_buenviaje_imagen_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="nombre_cliente",
            field=models.CharField(
                blank=True,
                help_text="Nombre que aparece en portada y buen viaje del PDF. Se prellena con el nombre del lead, pero el asesor puede cambiarlo (ej. si la cotización va a nombre de otra persona distinta a quien contactó).",
                max_length=200,
            ),
        ),
    ]
