# Generated by Django 6.0.7 on 2026-08-17 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0017_cotizacion_nombre_cliente"),
        ("leads", "0004_lead_ultima_notif_asesor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                help_text="Opcional -- una cotización puede crearse sin vincularse a ningún lead existente, usando solo nombre_cliente.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cotizaciones",
                to="leads.lead",
            ),
        ),
    ]
