# Generated by Django 6.0.7 on 2026-08-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0018_alter_cotizacion_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelpartner",
            name="imagen_1",
            field=models.URLField(blank=True, help_text="Foto grande (arriba, ancha)."),
        ),
        migrations.AddField(
            model_name="hotelpartner",
            name="imagen_2",
            field=models.URLField(
                blank=True, help_text="Foto chica (abajo, izquierda)."
            ),
        ),
        migrations.AddField(
            model_name="hotelpartner",
            name="imagen_3",
            field=models.URLField(blank=True, help_text="Foto chica (abajo, derecha)."),
        ),
    ]
