# Generated by Django 6.0.7 on 2026-08-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0019_hotelpartner_imagen_1_hotelpartner_imagen_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="destino",
            field=models.TextField(blank=True),
        ),
    ]
