# Generated by Django 6.0.7 on 2026-08-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0020_alter_cotizacion_destino"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacionhotel",
            name="noches",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
